version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "charg-db"
    volumes: 
      - ./rest-api/charg-db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  charg-exp-mgr:
    build: .
    environment:
      DB_DRIVER: "mysql"
      DS_NAME: "root:Admin123@tcp(db:3306)/charg-db"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "Admin123"
      MYSQL_DB: "charg-db"
      MYSQL_USER: "root"
      MYSQL_PORT: "3306"
    depends_on:
      - db
    ports:
      - "9090:9090"