version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "charg-db"
    volumes: 
      - ./rest-api/charg-db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  charg-exp-mgr:
    build: .
    environment:
      DB_DRIVER: "mysql"
      DS_NAME: "root:Admin123@tcp(db:3306)/charg-db"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "Admin123"
      MYSQL_DB: "charg-db"
      MYSQL_USER: "root"
      MYSQL_PORT: "3306"
    depends_on:
      - db
    ports:
      - "9100:9100"
      
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
          - ./rest-api/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
          - prometheus_data:/prometheus
      command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
          - 9090:9090
      restart: always

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      volumes: 
          - grafana_data:/var/lib/grafana
          - ./grafana/provisioning:/etc/grafana/provisioning
      environment:
          - GF_AUTH_DISABLE_LOGIN_FORM=false
          - GF_AUTH_ANONYMOUS_ENABLED=false
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      ports:
          - 3000:3000        

volumes: 
    grafana_data:
    prometheus_data: