### 
GET http://localhost:9090/get HTTP/1.1

###

GET http://localhost:9090/get/0 HTTP/1.1

### 

GET http://localhost:9090/get/OYSHO HTTP/1.1


###
POST http://localhost:9090/add HTTP/1.1
content-type: application/json

{
    "vendor": "PAF",
     "value": 12.3
}

###

PUT http://localhost:9090/update/2 HTTP/1.1
content-type: application/json

{
    "vendor": "GroceryStore",
    "description": "Super Market",
    "value": 75
}

###

GET http://localhost:9090/delete/2 HTTP/1.1

###

GET http://localhost:9090/clearall HTTP/1.1

###